Amlak/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('melk/', include('melk.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

melk/urls.py
from django.urls import path
from . import views

app_name = 'AMLAKAPP'
urlpatterns = [
    path('', views.melk_list, name='list'),
    path('<slug>', views.melk_details, name='slug')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'USER'
urlpatterns = [
    path('register', views.user_register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
]

melk/models.py
from django.db import models
import datetime

class Amlak(models.Model):
    YEAR_CHOICE = []
    for i in range(1800, datetime.datetime.now().year+1):
        YEAR_CHOICE.append((i, i))

    TYPE_CHOICE = [
        ('r', 'Rahn'),
        ('e', 'Ejare'),
        ('f', 'Forush'),
    ]
    Title = models.CharField(max_length=100)
    Slug = models.SlugField()
    Metre = models.IntegerField()
    Description = models.TextField()
    Image = models.ImageField(default='default.jpg', blank=True)
    Year = models.IntegerField(choices=YEAR_CHOICE, default=datetime.datetime.now().year)
    Publish = models.DateTimeField(auto_now_add=True)
    Update = models.DateTimeField(auto_now=True)
    Type = models.CharField(max_length=1, choices=TYPE_CHOICE)

    def __str__(self):
        return self.Title

    def show(self):
        return self.Description[:40] +' ...'

user/models.py
from django.db import models

# Create your models here.

Amlak/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

melk/views.py
from django.shortcuts import render
from . import models

def melk_list(request):
    AMLAK = models.Amlak.objects.all().order_by('-Publish')
    return render(request, 'melk/melk_list.html', {'AMLAK': AMLAK})

def melk_details(request, slug):
    MELK = models.Amlak.objects.get(Slug=slug)
    return render(request, 'melk/melk_details.html', {'MELK': MELK})

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('AMLAKAPP:list')
    else:
        form = UserCreationForm()
    return render(request, 'user/user_register.html', {'FORM': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('AMLAKAPP:list')
    else:
        form = AuthenticationForm()
    return render(request, 'user/user_login.html', {'FORM': form})

def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('AMLAKAPP:list')

melk/templates/melk/melk_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
    <h1>{{ MELK.Title }}</h1>
    <p>{{ MELK.Description }}</p>
    <img style="width: 100px; height: 80px;" src="{{ MELK.Image.url }}">
</body>
</html>

melk/templates/melk/melk_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Amlak</title>
    <link rel="stylesheet" href="{% static 'List.css' %}">
</head>
<body>
    {% for x in AMLAK %}
        <h1><a href="{% url 'AMLAKAPP:slug' slug=x.Slug %}">{{ x.Title }}</a></h1>
        <p>{{ x.show }}</p>
        <p>{{ x.Publish }}</p>
    {% endfor %}
    <div>
        <form method="post" action="{% url 'USER:logout' %}">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    </div>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
    <link rel="stylesheet" href="{% static 'MainStyle.css' %}">
</head>
<body>
    <h1>Home page</h1>
</body>
</html>

user/templates/user/user_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <form action="{% url 'USER:login' %}" method="post">
        {{ FORM }}
        {% csrf_token %}
        <input value="Login" type="submit">
    </form>
</body>
</html>

user/templates/user/user_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
   <form action="{% url 'USER:register' %}" method="post">
       {{ FORM }}
       {% csrf_token %}
       <input type="submit" value="Register">
   </form>
</body>
</html>